[package]
name = "rtow-rs"
version = "0.1.0"
authors = ["blackspotbear <blackspotbear@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
rand = "0.6.1"
cgmath = "0.16.1"
pbr = "1.0.1"
